### ISSUE TITLE
Crashes when you input an expression

### ISSUE THREAD

**Issue by littlepig453** [Qalculate/qalculate-qt#143] opened 2024-06-28 21:35 UTC
Rest of the app works fine until I press enter after entering in a simple expression, e.g. "3+4". I'm using arch and crash only happened after I updated libqalculate through pacman. The version on arch is 5.2.0-1 ([here](https://archlinux.org/packages/extra/x86_64/libqalculate/ "here")), while the most recent **release** version on Github is 5.1.1. I don't know if that makes a difference. However, there is a "v5.2.0" tagged on the libqalculate repo on Github which the PKGBUILD and .SRCINFO on arch servers use. Here is the journalctl dump:

Jun 28 16:32:53 [HOSTNAME GOES HERE] systemd-coredump[2617]: [🡕] Process 2602 (qalculate-qt) of user 1000 dumped core.
                                                      
                                                      Stack trace of thread 2602:
                                                      #0  0x000076261f546a0b n/a (libqalculate.so.23 + 0x146a0b)
                                                      #1  0x000076261f63afda _ZN13KnownVariable7setUnitENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE (libqalculate.so.23 + 0x23afda)
                                                      #2  0x000059622de0b8e8 n/a (qalculate-qt + 0x1658e8)
                                                      #3  0x000059622de0b992 n/a (qalculate-qt + 0x165992)
                                                      #4  0x000059622de0b992 n/a (qalculate-qt + 0x165992)
                                                      #5  0x000059622de0eb1e n/a (qalculate-qt + 0x168b1e)
                                                      #6  0x000059622de022a4 n/a (qalculate-qt + 0x15c2a4)
                                                      #7  0x000059622ddf2741 n/a (qalculate-qt + 0x14c741)
                                                      #8  0x000076261fda194a n/a (libQt6Core.so.6 + 0x1a194a)
                                                      #9  0x0000762620f4bd94 _ZN7QWidget5eventEP6QEvent (libQt6Widgets.so.6 + 0x14bd94)
                                                      #10 0x0000762620fe2838 _ZN6QFrame5eventEP6QEvent (libQt6Widgets.so.6 + 0x1e2838)
                                                      #11 0x0000762620efc51c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt6Widgets.so.6 + 0xfc51c)
                                                      #12 0x0000762620f01c52 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt6Widgets.so.6 + 0x101c52)
                                                      #13 0x000076261fd44d28 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt6Core.so.6 + 0x144d28)
                                                      #14 0x0000762620f635b6 n/a (libQt6Widgets.so.6 + 0x1635b6)
                                                      #15 0x0000762620efc51c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt6Widgets.so.6 + 0xfc51c)
                                                      #16 0x000076261fd44d28 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt6Core.so.6 + 0x144d28)
                                                      #17 0x00007626205785e4 _ZN22QGuiApplicationPrivate15processKeyEventEPN29QWindowSystemInterfacePrivate8KeyEventE (libQt6Gui.so.6 + 0x1785>
                                                      #18 0x00007626205e5d64 _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt6Gui.so.6 + >
                                                      #19 0x000076261b36f637 n/a (libQt6XcbQpa.so.6 + 0x51637)
                                                      #20 0x000076261fb0ea89 n/a (libglib-2.0.so.0 + 0x5ca89)
                                                      #21 0x000076261fb709b7 n/a (libglib-2.0.so.0 + 0xbe9b7)
                                                      #22 0x000076261fb0df95 g_main_context_iteration (libglib-2.0.so.0 + 0x5bf95)
                                                      #23 0x000076261ffa2cbd _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt6Core.so.6 + 0x3a2cbd)
                                                      #24 0x000076261fd4f01e _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x14f01e)
                                                      #25 0x000076261fd4934d _ZN16QCoreApplication4execEv (libQt6Core.so.6 + 0x14934d)
                                                      #26 0x000059622dd0e525 n/a (qalculate-qt + 0x68525)
                                                      #27 0x000076261ee39c88 n/a (libc.so.6 + 0x25c88)
                                                      #28 0x000076261ee39d4c __libc_start_main (libc.so.6 + 0x25d4c)
                                                      #29 0x000059622dd11255 n/a (qalculate-qt + 0x6b255)
                                                      
                                                      Stack trace of thread 2603:
                                                      #0  0x000076261ef1c39d __poll (libc.so.6 + 0x10839d)
                                                      #1  0x000076261fb708fd n/a (libglib-2.0.so.0 + 0xbe8fd)
                                                      #2  0x000076261fb0df95 g_main_context_iteration (libglib-2.0.so.0 + 0x5bf95)
                                                      #3  0x000076261ffa2cbd _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt6Core.so.6 + 0x3a2cbd)
                                                      #4  0x000076261fd4f01e _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x14f01e)
                                                      #5  0x000076261fe3a410 _ZN7QThread4execEv (libQt6Core.so.6 + 0x23a410)
                                                      #6  0x000076261f375e4e n/a (libQt6DBus.so.6 + 0x2de4e)
                                                      #7  0x000076261fec9747 n/a (libQt6Core.so.6 + 0x2c9747)

Thanks in advance

edit:
If its run by the terminal, it gives a little more info on the crash:

[user@hostname ~]$ qalculate-qt
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
[user@hostname ~]$

**Comment by hanna-kn** [comment] 2024-06-29 05:07
The tag was created in preparation for the release on Monday (2024-07-01).
The crash was caused by unintended binary incompatibility with the new version of libqalculate. This has now been fixed (https://github.com/Qalculate/libqalculate/commit/bf5d1537a21647631d4ecbd9e5a13be81957a04f).

**Comment by hanna-kn** [comment] 2024-06-29 14:53
Should be fixed in libqalculate-5.2.0.1 Arch package. I added v5.2.0.1 tag specifically for Arch Linux. I'm not sure exactly how the package handles new tags and if updating of the 5.2.0 tag would have been enough.

**Closed as completed** 2024-06-29 15:36 UTC
