### ISSUE TITLE
currency selection crash

### ISSUE THREAD

**Issue by ariefra** [Qalculate/qalculate-qt#71] opened 2022-12-03 04:50 UTC
Hi,

First, I would like to thank you for this great software.
I have following issue, which iirc start after 4.4.0 release:

When doing currency conversion selection in qalculate-qt under linux, a crash with sigsegv occur.

Host System: archlinux fully updated as of today.
qalculate-qt: version 4.4.0-1, ~/.config/qalculate-qt deleted (default)

How to replicate:
- Open qalculate-qt from terminal (or anywhere)
- type: 100 yen to 
- wait till currency selection visible
- type any letter
- qalculate-qt will start to hang, and then crash

Upon checking with strace, lots of following operation occur, during hang:
```
write(15, "\1", 1)                      = 1
write(15, "\240\254\272\323\24\5\0\0", 8) = 8
clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=10000000}, NULL) = 0
```

Final exit status from strace are:
```
clock_gettime(CLOCK_MONOTONIC, {tv_sec=26190, tv_nsec=284710949}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=26190, tv_nsec=284808727}) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x748cd5f5e518} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

**Comment by hanna-kn** [comment] 2022-12-03 07:43
I'm unable to reproduce this (with the Arch Linux qalculate-qt and libqalculate packages).

Does it not crash if currency selection is not visible when you type the letter?
Does it crash if you type a digit, or a letter which produces no matches, e.g. © (AltGr + C)?
Does it crash if you try to convert from a different currency, or a non-currency unit (e.g. m)?
Does it make any difference if you remove (or temporarily move) ~.local/share/qalculate?
Does it make any difference if you make changes to the completion settings (in the expression entry context menu)?
Are you using the latest Arch Linux libqalculate package, and there are no leftover versions of the library anywhere (if you've at one point compiled libqalculate yourself)?
Which Qt 6 theme are you using?

**Comment by ariefra** [comment] 2022-12-05 17:29
> Does it not crash if currency selection is not visible when you type the letter?
it does not crash, i.e. type "100 yen to", wait, then type space+any letter (matching or not matching)

>Does it crash if you type a digit, or a letter which produces no matches, e.g. © (AltGr + C)?
it does not crash, I type a number, 1 or letter q
matching letter produce crash

>Does it crash if you try to convert from a different currency, or a non-currency unit (e.g. m)?
with out showing currency selection it does not crash
typing m with currency selection visible will crash

>Does it make any difference if you remove (or temporarily move) ~.local/share/qalculate?
same issue, it still crash

>Does it make any difference if you make changes to the completion settings (in the expression entry context menu)?
no completion does not crash
any other completion produce crash
disabling delayed completion accellerate crash

>Are you using the latest Arch Linux libqalculate package, and there are no leftover versions of the library anywhere (if you've at one point compiled libqalculate yourself)?
I use latest libqalculate 4.4.0-2 from repository, self compiled libqalculate does not exist on the system. 

>Which Qt 6 theme are you using?
I use plasma on wayland, breeze dark theme, no qt6 theme exist.
I still have Qt5 libs on the system for plasma.
only default theme available, no custom plasma/gtk/qt theme exist.

**Comment by hanna-kn** [comment] 2022-12-05 18:48
I've now been able to reproduce the bug when running qalculate-qt in Plasma on Wayland. Wayland seems to cause different issues with completion depending on which compositor is used. My recommendation for now is therefore that you set QT_QPA_PLATFORM to xcb for qalculate-qt.

**Comment by ariefra** [comment] 2022-12-06 10:59
thank you, confirmed, running with:
```
QT_QPA_PLATFORM=xcb qalculate-qt
```
works around the issues

**Comment by hanna-kn** [comment] 2022-12-06 15:24
I've now fixed most issues with completion on Plasma with wayland platform plugin.

There are still serious issues on other desktops with wayland platform plugin. In Gnome, qalculate-qt will crash in some cases when the window is close to the bottom of the screen (when completion list is opened above cursor). With the Weston compositor completion does not work at all.

**Closed** 2022-12-25 23:25 UTC
